=== drronidz/XML-and-XSD-Crash-Course/patient.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema
        xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.bharatthippireddy.com/Patient"
        xmlns:tns="http://www.bharatthippireddy.com/Patient"
        elementFormDefault="unqualified">
    <element name="patient" type="tns:Patient"/>
    <complexType name="Patient">
        <sequence>
            <element name="id" type="tns:ID" minOccurs="1" maxOccurs="1"/>
            <element name="firstName" type="tns:String15Chars" minOccurs="1" maxOccurs="1"/>
            <element name="lastName" type="tns:String15Chars" minOccurs="1" maxOccurs="1"/>
            <element name="age" type="int" minOccurs="1" maxOccurs="1"/>
            <element name="birthDate" type="date" minOccurs="1" maxOccurs="1"/>
            <element name="email" type="string" minOccurs="1" maxOccurs="1"/>
            <element name="address" type="string" maxOccurs="unbounded"/>
            <element name="gender" type="tns:Gender" maxOccurs="1"/>
            <element name="phone" type="string" minOccurs="1" maxOccurs="1"/>
            <element name="payment" type="tns:PaymentType" minOccurs="1" maxOccurs="1"/>
        </sequence>
        <attribute name="id" type="tns:ID" use="required"/>
    </complexType>

    <complexType name="PaymentType">
        <choice>
            <element name="cash" type="double"/>
            <element name="insurance" type="tns:Insurance"/>
        </choice>
    </complexType>

    <complexType name="Insurance">
        <all>
            <element name="provider" type="string"/>
            <element name="limit" type="int"/>
        </all>
    </complexType>

    <simpleType name="ID">
        <restriction base="int">
            <pattern value="[0-9]*"/>
        </restriction>
    </simpleType>

    <simpleType name="String15Chars">
        <restriction base="string">
            <maxLength value="15"/>
        </restriction>
    </simpleType>

    <simpleType name="Gender">
        <restriction base="string">
            <enumeration value="Male"/>
            <enumeration value="Female"/>
        </restriction>
    </simpleType>


</schema>

=== drronidz/XML-and-XSD-Crash-Course/example_one(patient)/patient.xml
<patient
        xmlns:pat="http://www.bharatthippireddy.com/Patient"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.bharatthippireddy.com/Patient patient.xsd">
    <id>3</id>
    <firstName>diab</firstName>
    <lastName>abdelhalim</lastName>
    <age>3</age>
    <birthDate>2008-09-29</birthDate>
    <email>string</email>
    <address>Sayeh ABDALLAH STREET</address>
    <gender>Male</gender>
    <phone>string</phone>
    <payment>
        <insurance>
            <provider>Axa</provider>
            <limit>1000</limit>
        </insurance>
    </payment>
</patient>

=== drronidz/XML-and-XSD-Crash-Course/patient.xml
<pat:patient
        xmlns:pat="http://www.bharatthippireddy.com/Patient"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.bharatthippireddy.com/Patient patient.xsd">
    <pat:id>3</pat:id>
    <pat:firstName>diab</pat:firstName>
    <pat:lastName>abdelhalim</pat:lastName>
    <pat:age>3</pat:age>
    <pat:birthDate>2008-09-29</pat:birthDate>
    <pat:email>string</pat:email>
    <pat:address>Sayeh ABDALLAH STREET</pat:address>
    <pat:gender>Male</pat:gender>
    <pat:phone>string</pat:phone>
    <pat:payment>
        <pat:insurance>
            <pat:provider>Axa</pat:provider>
            <pat:limit>1000</pat:limit>
        </pat:insurance>
    </pat:payment>
</pat:patient>

=== drronidz/XML-and-XSD-Crash-Course/1/patient.xml
<patient
        xmlns:tns="http://www.bharatthippireddy.com/Patient"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.bharatthippireddy.com/Patient patient.xsd" id="123">
    <tns:id>3</tns:id>
    <tns:firstName>diab</tns:firstName>
    <tns:lastName>abdelhalim</tns:lastName>
    <tns:age>3</tns:age>
    <tns:birthDate>2008-09-29</tns:birthDate>
    <tns:email>string</tns:email>
    <tns:address>Sayeh ABDALLAH STREET</tns:address>
    <tns:gender>Male</tns:gender>
    <tns:phone>string</tns:phone>
    <tns:payment>
        <tns:insurance>
            <tns:provider>Axa</tns:provider>
            <tns:limit>1000</tns:limit>
        </tns:insurance>
    </tns:payment>
</patient>
